language: scala
sudo: false
jdk:
  - oraclejdk8
# This skips the install step.
# See https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Ste
install: true
script: $SCRIPT
env:
  matrix:
    - SCRIPT="mvn test -B"
    - SCRIPT="./sbt-build"
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.nvm
    - $HOME/.sbt/launchers
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.m2/repository/com/lightbend/lagom/sample/chirper
  - rm -rf $HOME/.ivy2/cache/com/lightbend/lagom/sample/chirper
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/773aba95141768c32dae
    on_success: always
    on_failure: always
